[project]
authors = [
	{ name = "long2ice", email = "long2ice@gmail.com" },
	{ name = "Robbie Capps", email = "robbie@pfun.me" }
]
description = "A fast admin dashboard based on FastAPI and TortoiseORM with tabler ui, inspired by Django admin."
documentation = "https://fastapi-admin.github.io"
homepage = "https://github.com/pfun-health/fastapi-admin"
keywords = ["fastapi", "admin", "dashboard", "tortoise-orm"]
license = "Apache-2.0"
name = "fastapi-admin"
packages = [
    { include = "fastapi_admin" },
]
readme = "README.md"
repository = "https://github.com/pfun-health/fastapi-admin.git"
version = "1.0.7"
dependencies = [
    "aiofiles>=25.1.0",
    "babel>=2.18.0",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.129.0",
    "jinja2>=3.1.6",
    "pendulum>=3.2.0",
    "python-multipart>=0.0.22",
    "redis>=7.2.0",
    "tortoise-orm>=1.1.4",
]

[build-system]
requires = ["hatchling", "wheel", "setuptools"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    # test
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "pytest-xdist",
    # lint
    "black",
    "flake8",
    "isort",
    "pylint",
    # example
    "asyncmy",
    "asyncpg",
    "python-dotenv",
    "mypy",
    "uvicorn>=0.41.0",
    "ipython>=9.10.0",
]
