[project]
authors = [
	{ name = "long2ice", email = "long2ice@gmail.com" },
	{ name = "Robbie Capps", email = "robbie@pfun.me" }
]
description = "A fast admin dashboard based on FastAPI and TortoiseORM with tabler ui, inspired by Django admin."
documentation = "https://fastapi-admin.github.io"
homepage = "https://github.com/pfun-health/fastapi-admin"
keywords = ["fastapi", "admin", "dashboard", "tortoise-orm"]
license = "Apache-2.0"
name = "fastapi-admin"
packages = [
    { include = "fastapi_admin" },
]
readme = "README.md"
repository = "https://github.com/pfun-health/fastapi-admin.git"
version = "1.0.6"

[dependencies]
Babel = "*"
aiofiles = "*"
redis = "*"
bcrypt = "*"
fastapi = "*"
jinja2 = "*"
python = "^3.10"
python-multipart = "*"
tortoise-orm = "*"
uvicorn = { version = "*", extras = ["standard"] }
pendulum = "*"

[build-system]
requires = ["hatchling", "wheel", "setuptools"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    # test
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "pytest-xdist",
    # lint
    "black",
    "flake8",
    "isort",
    "pylint",
    # example
    "asyncmy",
    "asyncpg",
    "python-dotenv",
    "mypy",
]
